### ISSUE TITLE
디폴트 아이템 선정

### ISSUE THREAD

**Issue by ye-geeee** [TTeYY/zipzup#36]
- 주소
- 아파트 이름
- 동
- 호수
- 면적
- 부동산
- 날짜
- 방향
- 층(저층, 고층)
- 채광
- 조망
- 주차
- 지하주차장
- 입지
- 수리여부
- 확장여부
- 기타
- 아파트 연식
- 호가

![1678319613677.jpg](https://user-images.githubusercontent.com/60929159/223879542-5ac576b2-b38e-4f9a-bd15-4ce05f2cd706.jpg)

**Comment by pooi** [comment]
https://github.com/TTeYY/zipzup/pull/43/files 이 내용으로 확정 완료
